# Generated by Django 2.2.6 on 2019-12-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
        ),
    ]
